### PR TITLE
fix: rename useMeta to useHead

### PR DESCRIPTION
**Pull request by Intevel**
The `useMeta` property has been renamed to `useHead`. Without this change the module would be broken with the latest framework version.

Regarding to this: https://github.com/nuxt/framework/pull/4066

### CODE REVIEW

**Review by danielroe — APPROVED** [review]
Thanks!

**Comment by Intevel** [comment]
I will fix the lint errors later

**Comment by Intevel** [comment]
Thanks for fixing the lint errors. @danielroe 💚

**Comment by danielroe** [comment]
(The issue was that the version of nuxt3 in this PR didn't have a `useHead` export.)

**Comment by Intevel** [comment]
@danielroe Any chance to merge this?

**Pull request merged**
